backend:
  name: git-gateway
  branch: master

media_folder: "public/images"

collections:
  - name: "incidents"
    label: "Incidents"
    format: "json"
    label_singular: "Incident"
    folder: "data/incidents"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: "name"
    editor:
      preview: false
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
      - label: "Impact"
        name: "impact"
        widget: "select"
        options:
          - { label: "None", value: "none" }
          - { label: "Minor", value: "minor" }
          - { label: "Major", value: "major" }
          - { label: "Critical", value: "critical" }
      - label: "Updates"
        name: "updates"
        widget: "list"
        fields:
          - label: "Content"
            name: "content"
            widget: "text"
          - label: "Status"
            name: "status"
            widget: "select"
            options:
              - { label: "Investigating", value: "investigating" }
              - { label: "Identified", value: "identified" }
              - { label: "Monitoring", value: "monitoring" }
              - { label: "Resolved", value: "resolved" }
          - label: "Date"
            name: "date"
            widget: "datetime"

  - name: "scheduledmaintenance"
    label: "Scheduled maintenance"
    format: "json"
    folder: "data/maintenances"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: "name"
    editor:
      preview: false
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
      - label: "Scheduled time"
        name: "scheduledTime"
        widget: "datetime"
      - label: "For"
        name: "minutes"
        hint: "Time expressed in minutes"
      - label: "Content"
        name: "content"
        widget: "text"
      - label: "Components that are going to be affected"
        name: "components"
        widget: "select"
        multiple: true
        options:
          - { label: "Content Delivery API", value: "cda" }
          - { label: "Content Management API", value: "cma" }
          - { label: "Assets CDN (Imgix)", value: "imgix" }
          - { label: "Projects administrative interface", value: "backend" }
          - { label: "DNS", value: "dns" }
      - label: "Updates"
        name: "updates"
        required: false
        widget: "list"
        fields:
          - label: "Content"
            name: "content"
            widget: "text"
          - label: "Date"
            name: "date"
            widget: "datetime"
          - label: "Status"
            name: "status"
            widget: "select"
            options:
              - { label: "Scheduled", value: "scheduled" }
              - { label: "In progress", value: "in-progress" }
              - { label: "Verifying", value: "verifying" }
              - { label: "Completed", value: "completed" }
